stages:
  - prep
  - build
  - test

preparar carro:
  stage: prep
  script:
    - mkdir build
    - cd build
    - touch car.txt
  artifacts:
    paths:
      - build/

construir carro:
  stage: build
  script:
    - cd build
    - echo "chassis" >> car.txt
    - echo "engine" >> car.txt
    - echo "wheels" >> car.txt
  dependencies:
    - prep
  artifacts:
    paths:
      - build/

assinar carro:
  stage: build
  script:
    - mkdir meta
    - cd meta
    - echo $GITLAB_USER_NAME > author.txt
  dependencies:
    - prep
  artifacts:
    paths:
      - meta/

testar carro:
  stage: test
  script:
    - test -f build/car.txt
    - cd build
    - grep "chassis" car.txt
    - grep "engine" car.txt
    - grep "wheels" car.txt
  dependencies:
    - build